version: '3'

services:
  tagging-api:
    image: saladtechnologies/image-segmentation-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7999:7999
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
